# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Moviment')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('document', models.CharField(max_length=10, verbose_name='Document')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='moviment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryType'),
        ),
    ]
