# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160928_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
