# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161006_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
    ]
