# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='despesas',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='rendimentos',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rendimento'),
        ),
    ]
