# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161115_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='despesas',
            new_name='despesa',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='rendimentos',
            new_name='rendimento',
        ),
    ]
