# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161115_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo'),
            preserve_default=False,
        ),
    ]
